# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: linux class
subtitle: "种树最好的时间是十年前 其次是现在"
description: "GitHub - luo_u个人博客"
keywords: luo_u linux
timezone: '+0800'
encoding: "utf-8"
side_bar_repo_limit: 5
repository: luouu/luouu.github.io


# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 组件配置
components:
    # 分享
    share:
        enabled: true
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2021-02-15
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true

# ---------------- #
#      Author      #
# ---------------- #
author: luo_u
organization: 
organization_url: 
github_username: luouu
location: Shengzheng, China
email: luo_u@qq.com
# weibo_username:     luo_u
# zhihu_username:     luo_u
# linkedin_username:  luo_u
# google_userId:   101388994961262711072
# twitter_username:  luo_u


# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 博客

  -
    href: /categories/
    label: 分类

  -
    href: /cmd/
    label: linux命令

  -
    href: /res/
    label: 资源

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 20
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins_dir:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions

collections:
    cmd:
        output: true
        permalink: /cmd/:path/

    tool:
        output: true
        permalink: /tool/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jijiucheng
    repo: blog-comments
    oauth:
        client_id: 0c478d9a528799ea0055
        client_secret: 814f60320dfdcafe2a4bca07e978e52cef309f61
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jijiucheng
    repo: blog-comments
    clientID: 359b06ea524a7700164d
    clientSecret: 306575c0f8ef949e860ca7012153ea30580a1502
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 20

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true
        content_header: true
        content_footer: false

gems: [jekyll-paginate]
